ruby '3.0.0'
source 'https://rubygems.org'

gem 'sinatra', '~> 2.2'
gem 'sinatra-contrib', '~> 2.2'
gem 'webrick', '~> 1.7'

group :development do
  gem 'debase'
  gem 'fastri'
  gem 'rcodetools'
  gem 'rubocop'
  gem 'ruby-debug-ide'
end
